#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GladiatorApp.Droid.Resource", IsApplication=true)]

namespace GladiatorApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_dialog_actioned_on_disabled_toast = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_dialog_actioned_on_disabled_toast;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_download_progress_number_format = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_download_progress_number_format;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_downloading_mandatory_update = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_downloading_mandatory_update;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_install = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_install;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_install_ready_message = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_install_ready_message;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_install_ready_title = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_install_ready_title;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_notification_category = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_notification_category;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_unknown_sources_dialog_message = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_unknown_sources_dialog_message;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_unknown_sources_dialog_settings = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_unknown_sources_dialog_settings;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_download = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_download;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_message_mandatory = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_message_mandatory;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_message_optional = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_message_optional;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_postpone = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_postpone;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_title = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_title;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_dialog_view_release_notes = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_dialog_view_release_notes;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_failed_dialog_ignore = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_failed_dialog_ignore;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_failed_dialog_message = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_failed_dialog_message;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_failed_dialog_reinstall = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_failed_dialog_reinstall;
			global::Microsoft.AppCenter.Distribute.Resource.String.appcenter_distribute_update_failed_dialog_title = global::GladiatorApp.Droid.Resource.String.appcenter_distribute_update_failed_dialog_title;
			global::Microsoft.AppCenter.Push.Android.Resource.Drawable.ic_stat_notify_dot = global::GladiatorApp.Droid.Resource.Drawable.ic_stat_notify_dot;
			global::Microsoft.AppCenter.Push.Android.Resource.String.library_name = global::GladiatorApp.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_stat_notify_dot = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050015
			public const int app_name = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int appcenter_distribute_dialog_actioned_on_disabled_toast = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int appcenter_distribute_download_progress_number_format = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int appcenter_distribute_downloading_mandatory_update = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int appcenter_distribute_install = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int appcenter_distribute_install_ready_message = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int appcenter_distribute_install_ready_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int appcenter_distribute_notification_category = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int appcenter_distribute_unknown_sources_dialog_message = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int appcenter_distribute_unknown_sources_dialog_settings = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int appcenter_distribute_update_dialog_download = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int appcenter_distribute_update_dialog_message_mandatory = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int appcenter_distribute_update_dialog_message_optional = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int appcenter_distribute_update_dialog_postpone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int appcenter_distribute_update_dialog_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int appcenter_distribute_update_dialog_view_release_notes = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int appcenter_distribute_update_failed_dialog_ignore = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int appcenter_distribute_update_failed_dialog_message = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int appcenter_distribute_update_failed_dialog_reinstall = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int appcenter_distribute_update_failed_dialog_title = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hello = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
